# This dockerfile is based on Microsoft's implementation
# See https://github.com/Microsoft/iis-docker

FROM cloud.canister.io:5000/schwindelig/whalecore-base-windows-server:latest

RUN powershell -Command Add-WindowsFeature Web-Server

COPY /Whalecore C:\Whalecore

EXPOSE 80

ENTRYPOINT ["C:\Wahlecore\Bin\ServiceMonitor.exe", "w3svc"]