# This dockerfile is based on Microsoft's implementation
# See https://github.com/Microsoft/iis-docker

FROM whalecore.azurecr.io/whalecore-base-windows-server:latest

# Switch to powershell
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

# Copy context
COPY /Whalecore C:\Whalecore

# Run DSC
RUN C:\Whalecore\Scripts\DSC-Whalecore-Base-IIS.ps1

EXPOSE 80

ENTRYPOINT ["C:\\Whalecore\\Bin\\ServiceMonitor.exe", "w3svc"]